//LOCALHOST 
###
http://localhost:8080/contacts/

###
http://localhost:8080/contacts/6a052c5c9abf4bb8b03911e1

###
http://localhost:8080/contacts/6a052c5c9abf4bb8b03911e2

###
http://localhost:8080/contacts/6a052c5c9abf4bb8b03911e3

//PRODUCTION
###
https://cse-341-spring26.onrender.com/contacts
###
https://cse-341-spring26.onrender.com/contacts/6a052c5c9abf4bb8b03911e1
###
https://cse-341-spring26.onrender.com/contacts/6a052c5c9abf4bb8b03911e2
###
https://cse-341-spring26.onrender.com/contacts/6a052c5c9abf4bb8b03911e3


### Create a new contact
POST http://localhost:8080/contacts/ HTTP/1.1 
Content-Type: application/json

{
"firstName": "Omarlin",
"lastName": "Parra",
"email": "omarlin@hola.net",
"favoriteColor": "purple",
"birthday": "1995-05-20"
}


### Update a contact
PUT http://localhost:8080/contacts/6a0733b5b8735334e773a09f
Content-Type: application/json

{
"firstName": "jefferson",
"lastName": "Parra",
"email": "omarlin@hola.net",
"favoriteColor": "purple",
"birthday": "1995-05-20"
}

### Delete a contact
DELETE http://localhost:8080/contacts/6a0733b5b8735334e773a09f

##### PRODUCTION



### Create a new contact 
POST https://cse-341-spring26.onrender.com/contacts/ HTTP/1.1 
Content-Type: application/json

{
"firstName": "Omarlin",
"lastName": "Parra",
"email": "omarlin@hola.net",
"favoriteColor": "purple",
"birthday": "1995-05-20"
}


### Update a contact
PUT https://cse-341-spring26.onrender.com/contacts/
Content-Type: application/json

{
"firstName": "jefferson",
"lastName": "Parra",
"email": "jeff@hola.net",
"favoriteColor": "cyan",
"birthday": "1995-05-20"
}

### Delete a contact
DELETE https://cse-341-spring26.onrender.com/contacts/

